# declares neuroos system user(s)/group(s)
# Type  Name              ID    GECOS                          Home directory
u       neuroos-fetcher    -    "NeuroOS external fetcher (C7)" /var/spool/neuroos-fetcher
g       neuroos            -
m       neuroos-fetcher    neuroos
